################################################################################
#
#  Copyright (C) 2020 BadPixxel <www.badpixxel.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/3.0/gitlab/php/defaults.yaml'

################################################################
# Defined Pipeline Stages
stages:
    - Symfony-5
    - Symfony-6
    - Symfony-7

################################################################
# Symfony 7
################################################################

sf7:php-8.3:
    extends:          .quality
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    variables:
      SYMFONY_REQUIRE: 7.*

sf7:php-8.2:
    extends:          .quality
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    variables:
      SYMFONY_REQUIRE: 7.*

sf7:php-8.1:
    extends:          .quality
    stage:            Symfony-7
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
      SYMFONY_REQUIRE: 7.*

################################################################
# Symfony 6
################################################################

sf6:php-8.3:
    extends:          .quality
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3
    variables:
      SYMFONY_REQUIRE: 6.4.*

sf6:php-8.2:
    extends:          .quality
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    variables:
      SYMFONY_REQUIRE: 6.4.*

sf6:php-8.1:
    extends:          .quality
    stage:            Symfony-6
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
      SYMFONY_REQUIRE: 6.4.*

################################################################
# Symfony 5
################################################################

sf5:php-8.2:
    extends:          .quality
    stage:            Symfony-5
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
    variables:
        SYMFONY_REQUIRE: 5.4.*

sf5:php-8.1:
    extends:          .quality
    stage:            Symfony-5
    image:            registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    variables:
        SYMFONY_REQUIRE: 5.4.*
