
################################################################################
#
#  Copyright (C) 2020 BadPixxel <www.badpixxel.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

################################################################################
# Define Test Matrix
matrix:
    include:          
        # Symfony 3.4 Branch       
        - php: 7.3
          env: SF_VERSION="3.4.*"        

      # Symfony 4.4 Branch
        - php: 7.4
          env: SF_VERSION="4.4.*"

    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

before_install:
    # Disable Xdebug ...
    - phpenv config-rm xdebug.ini 
    # Setup Travis PHP     
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
      
# Install composer dependencies,
install:   
    - echo "Build Dependencies"
    # Setup Symfony Version if Required
    - if [ "$SF_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SF_VERSION; fi;
    - composer update  --prefer-dist --no-interaction
# Run script
script:
    # Execute Grump Full Testsuite 
    - php vendor/bin/grumphp run
    # Show Outdated Packages
    - composer outdated
    
################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty
################################################################################
# Start mysql service
services:
  - mysql
################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files
################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
################################################################################
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always