services:


    ############################################################################
    # Sendinblue Bridge Send Emails Admin Extension 
    badpixxel.sendinblue.admin.emails:
        class: BadPixxel\SendinblueBridge\Admin\UserEmailsAdmin
        arguments: 
            -   ~
            - %sendinblue_bridge.emails.class%
            - BadPixxel\SendinblueBridge\Controller\EmailAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: SendInBlue Emails, group: System, icon: '<i class="fa fa-server"></i>'  }
            
    ############################################################################
    # Sendinblue Bridge Emails Admin Extension for Users 
    badpixxel.sendinblue.admin.emails.extension:
        class: BadPixxel\SendinblueBridge\Admin\Extensions\UserEmailsExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.user.admin.user }  
            
    ############################################################################
    # Sendinblue Bridge Templates Admin Extension 
    badpixxel.sendinblue.admin.templates:
        class: BadPixxel\SendinblueBridge\Admin\TemplatesAdmin
        arguments: 
            -   ~
            - %sendinblue_bridge.emails.class%
            - BadPixxel\SendinblueBridge\Controller\TemplatesAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: SendInBlue Templates, group: System, icon: '<i class="fa fa-desktop"></i>'  }
            