services:
    _defaults:
        autowire:   true

    ############################################################################
    # Sendinblue Bridge Send Emails Admin Extension 
    badpixxel.sendinblue.admin.emails:
        class: BadPixxel\SendinblueBridge\Admin\UserEmailsAdmin
        arguments:
            - ~
            - "%sendinblue_bridge.emails.class%"
            - BadPixxel\SendinblueBridge\Controller\EmailAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: SendInBlue Emails, group: SendInBlue, icon: '<i class="fa far fa-envelope"></i>', pager_type: 'simple'  }

    ############################################################################
    # Sendinblue Bridge Send Sms Admin Extension
    badpixxel.sendinblue.admin.sms:
        class: BadPixxel\SendinblueBridge\Admin\UserSmsAdmin
        arguments:
            - ~
            - "%sendinblue_bridge.sms.class%"
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: SendInBlue Sms, group: SendInBlue, icon: '<i class="fa far fa-envelope"></i>', pager_type: 'simple'  }

    ############################################################################
    # Sendinblue Bridge Emails Admin Extension for Users 
    badpixxel.sendinblue.admin.emails.extension:
        class: BadPixxel\SendinblueBridge\Admin\Extensions\UserEmailsExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.user.admin.user }  

    ############################################################################
    # Sendinblue Bridge Sms Admin Extension for Users
    badpixxel.sendinblue.admin.sms.extension:
        class: BadPixxel\SendinblueBridge\Admin\Extensions\UserSmsExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.user.admin.user }

    ############################################################################
    # Sendinblue Bridge Templates Admin Extension 
    badpixxel.sendinblue.admin.templates:
        class: BadPixxel\SendinblueBridge\Admin\TemplatesAdmin
        arguments: 
            - ~
            - BadPixxel\SendinblueBridge\Models\AbstractEmail
            - BadPixxel\SendinblueBridge\Controller\TemplatesAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: SendInBlue Templates, group: SendInBlue, icon: '<i class="fa far fa-envelope"></i>'  }
            