services:
    _defaults:
        autowire:   true

    ########################################################################
    # Declare & AutoWire Bundle Commands
    BadPixxel\SendinblueBridge\Command\:
        resource: '../../Command'
        autowire:   true
        tags:       [ console.command ]

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\SendinblueBridge\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ################################################################################
    # Bridge Configurations Manager
    BadPixxel\SendinblueBridge\Services\ConfigurationManager:
        arguments:
            - "%sendinblue_bridge%"
            - "%mailer_disable%"
    
    ################################################################################
    # SendInBlue API Account Manager
    BadPixxel\SendinblueBridge\Services\AccountManager: ~

    ################################################################################
    # SendInBlue Emails SMTP Manager
    BadPixxel\SendinblueBridge\Services\SmtpManager:
        public: true

    ################################################################################
    # SendInBlue Sms Manager
    BadPixxel\SendinblueBridge\Services\SmsManager:
        public: true

    ################################################################################
    # SendInBlue Events Tracker Manager
    BadPixxel\SendinblueBridge\Services\EventManager:
        public: true

    ################################################################################
    # SendInBlue Emails Templates Manager
    BadPixxel\SendinblueBridge\Services\TemplateManager:
        public: true

    ################################################################################
    # SendInBlue Emails Templates Twig Extension
    badpixxel.sendinblue.extension:
        class: BadPixxel\SendinblueBridge\Twig\SendinblueBridgeExtension
        tags:
            - { name: twig.extension  }