
services:
    
    # Bridge Configurations Manager    
    badpixxel.sendinblue.configuration:
        class: BadPixxel\SendinblueBridge\Services\ConfigurationManager
        public: true
        arguments:
            - %sendinblue_bridge%
            - %swiftmailer.delivery.enabled%
    
    # SendInBlue API Account Manager    
    badpixxel.sendinblue.account:
        class: BadPixxel\SendinblueBridge\Services\AccountManager
        public: true
        autowire: true
        
    # SendInBlue Emails SMTP Manager    
    badpixxel.sendinblue.smtp:
        class: BadPixxel\SendinblueBridge\Services\SmtpManager
        public: true
        autowire: true 
        
    # SendInBlue Emails Templates Manager    
    badpixxel.sendinblue.templates:
        class: BadPixxel\SendinblueBridge\Services\TemplateManager
        public: true
        autowire: true         