services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ########################################################################
    # Declare & AutoWire Bundle Commands
    BadPixxel\BrevoBridge\Command\:
        resource: '../../Command'
        autowire:   true
        tags:       [ console.command ]

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\BrevoBridge\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments', 'container.service_subscriber']

    ################################################################################
    # Bridge Configurations Manager
    BadPixxel\BrevoBridge\Services\ConfigurationManager: ~

    ################################################################################
    # SendInBlue API Account Manager
    BadPixxel\BrevoBridge\Services\AccountManager: ~

    ################################################################################
    # SendInBlue Emails SMTP Manager
    BadPixxel\BrevoBridge\Services\SmtpManager:
        public: true

    ################################################################################
    # SendInBlue Sms Manager
    BadPixxel\BrevoBridge\Services\SmsManager:
        public: true

    ################################################################################
    # SendInBlue Events Tracker Manager
    BadPixxel\BrevoBridge\Services\EventManager:
        public: true

    ################################################################################
    # Emails Processor
    BadPixxel\BrevoBridge\Services\EmailProcessor: ~

    ################################################################################
    # Emails Templates Manager
    BadPixxel\BrevoBridge\Services\TemplateManager:
        public: true

    ################################################################################
    # Raw Html Renderer
    BadPixxel\BrevoBridge\Services\RawHtmlRenderer: ~

    ################################################################################
    # SendInBlue Emails Templates Twig Extension
    BadPixxel\BrevoBridge\Twig\BrevoBridgeExtension:
        tags:
            - { name: twig.extension  }