services:
    _defaults:
        autowire:   true

    ########################################################################
    # Declare & AutoWire Bundle Commands
    BadPixxel\BrevoBridge\Command\:
        resource: '../../Command'
        autowire:   true
        tags:       [ console.command ]

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\BrevoBridge\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments', 'container.service_subscriber']

    ################################################################################
    # Bridge Configurations Manager
    BadPixxel\BrevoBridge\Services\ConfigurationManager:
        arguments:
            - "%brevo_bridge%"

    ################################################################################
    # SendInBlue API Account Manager
    BadPixxel\BrevoBridge\Services\AccountManager: ~

    ################################################################################
    # SendInBlue Emails SMTP Manager
    BadPixxel\BrevoBridge\Services\SmtpManager:
        public: true

    ################################################################################
    # SendInBlue Sms Manager
    BadPixxel\BrevoBridge\Services\SmsManager:
        public: true

    ################################################################################
    # SendInBlue Events Tracker Manager
    BadPixxel\BrevoBridge\Services\EventManager:
        public: true

    ################################################################################
    # SendInBlue Emails Templates Manager
    BadPixxel\BrevoBridge\Services\TemplateManager:
        public: true

    ################################################################################
    # SendInBlue Emails Templates Twig Extension
    badpixxel.sendinblue.extension:
        class: BadPixxel\BrevoBridge\Twig\SendinblueBridgeExtension
        tags:
            - { name: twig.extension  }