services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ########################################################################
    # Declare & AutoWire Bundle Commands
    BadPixxel\BrevoBridge\Command\:
        resource: '../../Command'
        autowire:   true
        tags:       [ console.command ]

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\BrevoBridge\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments', 'container.service_subscriber']

    ################################################################################
    # AutoWire for Services
    BadPixxel\BrevoBridge\Services\:
        resource: '../../Services'

    ################################################################################
    # SendInBlue Emails Templates Twig Extension
    BadPixxel\BrevoBridge\Twig\BrevoBridgeExtension:
        tags:
            - { name: twig.extension  }

    ################################################################################
    # Register Twig String Loader Extension
    Twig\Extension\StringLoaderExtension: ~