
services:

    ################################################################################
    # AutoWire for Controllers
    BadPixxel\SendinblueBridge\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Bridge Configurations Manager    
    BadPixxel\SendinblueBridge\Services\ConfigurationManager:
        arguments:
            - "%sendinblue_bridge%"
            - "%swiftmailer.delivery.enabled%"
    
    # SendInBlue API Account Manager    
    BadPixxel\SendinblueBridge\Services\AccountManager:
        autowire: true
        
    # SendInBlue Emails SMTP Manager    
    BadPixxel\SendinblueBridge\Services\SmtpManager:
        autowire: true
        public: true

    # SendInBlue Emails Templates Manager    
    BadPixxel\SendinblueBridge\Services\TemplateManager:
        autowire: true
        public: true

    # SendInBlue Emails Templates Twig Extension
    badpixxel.sendinblue.extension:
        class: BadPixxel\SendinblueBridge\Twig\SendinblueBridgeExtension
        tags:
            - { name: twig.extension  }