################################################################################
#
#  Copyright (C) BadPixxel <www.badpixxel.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

services:

    ################################################################################
    # Develop Image
    app:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.3"
        init:           true
        container_name: dev.brevo-bridge.local
        hostname:       dev.brevo-bridge.local
        volumes:
            - ../:/var/www/html
        environment:
            SERVER_ROOT:        /var/www/html/tests/public
            SYMFONY_REQUIRE:    7.4.*
