################################################################################
#
#  Copyright (C) BadPixxel <www.badpixxel.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

services:

    ################################################################################
    # Symfony 5 + PHP 8.1
    sf5:
        image:          "registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1"
        init:           true
        container_name: sf5.brevo-bridge.local
        hostname:       sf5.revo-bridge.local
        volumes:
            - ../:/var/www/html
            - sf5-var:/var/www/html/var
            - sf5-vendor:/var/www/html/vendor
        environment:
            COMPOSER_ROOT_VERSION:  6.0.x-dev
            SERVER_ROOT:        /var/www/html/tests/public
            SYMFONY_REQUIRE:    5.4.*

volumes:
    sf5-var:        ~
    sf5-vendor:     ~